# action.yml
name: "Build OGC Application Package"
description: "A GitHub Action to build an OGC Application Package."
inputs:
  workflow-configuration-path:
    description: "Path to the workflow configuration YML file"
    required: true
  github-token:
    description: "GitHub token for authentication"
    required: true
  dockerfile-path:
    description: "Path to Dockerfile"
    required: true

# permissions:
#   contents: write

runs:
  using: "composite"
  steps:
    - name: Checkout repo content
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML ruamel.yaml
        pip list
      shell: bash

    - name: Print action inputs
      run: echo "Inputs ${{ inputs.dockerfile-path }}"
      shell: bash

    - name: Validate inputs
      run: echo "GITHUB_REPO_LOWER=${github.repository@L}" >>${GITHUB_ENV}
      shell: bash

    # - name: Generate build config for algorithm
    #   run: python3 ${{ github.action_path }}/generate_build_config.py nasa/algorithm_config.yml
    #   shell: bash

    # - name: Source build config environment variables
    #   uses: c-py/action-dotenv-to-setenv@v5
    #   with:
    #     env-file: ./.github/actions/.env

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and push algorithm Docker image
      id: push-algorithm
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile-path }}
        # build-args: |
        #   BASE_IMAGE_NAME=${{ env.BASE_IMAGE_NAME }}
        #   REPO_NAME=${{ env.REPO_NAME }}
        #   BRANCH=${{ env.BRANCH }}
        #   REPO_URL_WITH_TOKEN=${{ env.REPO_URL_WITH_TOKEN }}
        #   BUILD_CMD=${{ env.BUILD_CMD }}
        push: true
        tags: ghcr.io/${{ GITHUB_REPO_LOWER }}.${{ github.ref_name }}:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate OGC application package process CWL
      run: python3 ${{ github.action_path }}/build_cwl_workflow.py --yaml-file ${{ inputs.workflow-configuration-path }}
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    # - name: Configure Git
    #   run: |
    #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
    #     git config --global user.name "github-actions[bot]"
    #   shell: bash

    # - name: Commit and push workflow file
    #   run: |
    #     git add process.cwl
    #     git commit -m "Added process.cwl via github actions"
    #     git push
    #   shell: bash
