# action.yml
name: "Build OGC Application Package"
description: "A GitHub Action to build an OGC Application Package."
inputs:
  workflow-configuration-path:
    description: "Path to the workflow configuration YML file"
    required: true
  github-token:
    description: "GitHub token for authentication"
    required: true
  dockerfile-path:
    description: "Path to Dockerfile"
    required: true

# permissions:
#   contents: write

runs:
  using: "composite"
  steps:
    - name: Checkout repo content
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML ruamel.yaml
        pip list
      shell: bash

    - name: Create env variable of GitHub repo name to lowercase
      run: |
          GITHUB_REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "GITHUB_REPO_LOWER=$GITHUB_REPO_LOWER" >>${GITHUB_ENV}
      shell: bash

    - name: Set docker tag environment variable
      run: |
          echo "DOCKER_TAG=ghcr.io/${{ env.GITHUB_REPO_LOWER }}.${{ github.ref_name }}:latest" >>${GITHUB_ENV}
      shell: bash

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and push algorithm Docker image
      id: push-algorithm
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile-path }}
        push: true
        tags: ${{ env.DOCKER_TAG }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate OGC application package process CWL
      run: python3 ${{ github.action_path }}/build_cwl_workflow.py --yaml-file ${{ inputs.workflow-configuration-path }}
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    # - name: Configure Git
    #   run: |
    #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
    #     git config --global user.name "github-actions[bot]"
    #   shell: bash

    # - name: Commit and push workflow file
    #   run: |
    #     git add process.cwl
    #     git commit -m "Added process.cwl via github actions"
    #     git push
    #   shell: bash
