# action.yml
name: "Build OGC Application Package"
description: "A GitHub Action to build an OGC Application Package."
inputs:
  workflow-configuration-path:
    description: "Path to the workflow configuration YML file"
    required: true
  github-token:
    description: "GitHub token for authentication"
    required: true
  dockerfile-path:
    description: "Path to Dockerfile"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repo content
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML ruamel.yaml
        pip install cwltool
        pip install ogc_ap_validator
        pip list
      shell: bash

    - name: Create env variable of lowercase GitHub repo name
      run: |
          GITHUB_REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "GITHUB_REPO_LOWER=$GITHUB_REPO_LOWER" >>${GITHUB_ENV}
      shell: bash

    - name: Set docker tag environment variable
      run: |
          echo "DOCKER_TAG=ghcr.io/${{ env.GITHUB_REPO_LOWER }}.${{ github.ref_name }}:latest" >>${GITHUB_ENV}
      shell: bash

    - name: Set workflow file name environment variable
      run: |
          REPO_NAME=$(basename ${{ env.GITHUB_REPO_LOWER }})
          WORKFLOW_FILE_NAME="process_${REPO_NAME}_${GITHUB_REF_NAME}.cwl"
          WORKFLOW_FILE_NAME="${WORKFLOW_FILE_NAME//\//_}"
          echo "WORKFLOW_FILE_NAME=$WORKFLOW_FILE_NAME" >>${GITHUB_ENV}
      shell: bash

    - name: Generate OGC application package process CWL
      run: python3 ${{ github.action_path }}/build_cwl_workflow.py --yaml-file ${{ inputs.workflow-configuration-path }} --cwl-template-file  ${{ github.action_path }}/templates/process.v1_2.cwl
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Check output
      run: |
        ls -lrt workflows/
      shell: bash

    - name: Run CWL validator
      run: cwltool --validate --strict --verbose workflows/${{ env.WORKFLOW_FILE_NAME }}
      shell: bash

    - name: Run OGC validator
      run: ap-validator --detail all workflows/${{ env.WORKFLOW_FILE_NAME }}
      shell: bash

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and push algorithm Docker image
      id: push-algorithm
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile-path }}
        push: true
        tags: ${{ env.DOCKER_TAG }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Configure Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
      shell: bash

    - name: Commit and push workflow file
      run: |
        git pull
        git add workflows/${{ env.WORKFLOW_FILE_NAME }}
        git commit -m "Committed workflow via github actions"
        git push
      shell: bash
